### ISSUE TITLE
Can't run Gibber environment in master branch using localhost, external/script.min.js missing

### ISSUE THREAD

**Issue by alvarobyrne** [charlieroberts/Gibber#19]
Hi.
Don't know if this is really a bug, but , can't run Gibber environment in `master` branch using localhost (using node.js' [http-server](https://github.com/nodeapps/http-server)), `external/script.min.js` missing.
It does run at the `gibber2` branch.
Thanks

**Comment by charlieroberts** [comment]
This bug got lost... I have instructions for installing the server and populating the database here:

https://github.com/charlieroberts/gibber.server
