### ISSUE TITLE
Gibber server is down

### ISSUE THREAD

**Issue by radiodario** [charlieroberts/Gibber#23]
I'm trying to access gibber at http://gibber.mat.ucsb.edu/ but it looks to be down:

```
→ ping gibber.mat.ucsb.edu
PING gibber.mat.ucsb.edu (128.111.26.157): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
```

Is it being moved? thanks!

**Comment by charlieroberts** [comment]
Hi Dario,

Sorry about this... electricity to the campus where the server is hosted has been cut... it should be restored in three or four hours. However, I'm thinking about trying to move the server to a dedicated hosting facility to avoid these types of outages in the future.

I'll post back when the server is running again. - Charlie

**Comment by radiodario** [comment]
Thanks Charlie, hope you guys get power back soon!

**Comment by charlieroberts** [comment]
OK, it's back online!
