### ISSUE TITLE
Add microphone input

### ISSUE THREAD

**Issue by maciejjankowski** [charlieroberts/Gibber#28]
I wanted to use gibber for live coding video for external tracks.
If I wanted to add external audio for gibber processing (levels, fft?) where do I start?

**Comment by charlieroberts** [comment]
I'm not sure I understand the question perfectly, but the `Input()` unit generator gets input from whatever device is selected as the default audio driver on your computer (in OS X you can change this in AudioMIDI Setup). Does it do what you need?

**Comment by maciejjankowski** [comment]
OMG this is wicked cool! :D :dancers: 

how come I didn't find this in the documentation?

Where do I look for it? I didn't see things like `Add()` in the reference

**Comment by charlieroberts** [comment]
The documentation is woefully incomplete at the moment... it's something I'm hoping to remedy over the summer :(

Glad the audio input is working for you though!
