### ISSUE TITLE
Doesn't work any more in Windows 10 + Chrome Version 49.0.2623.75 m (64-bit).

### ISSUE THREAD

**Issue by Leetcore** [charlieroberts/Gibber#32]
I installed the Chrome update and it's now an error on http://gibber.mat.ucsb.edu/:
VM162:1 Uncaught SyntaxError: Identifier 'initSound' has already been declared

I don't know if this is a problem in Chrome. It seams like Chrome is also not playing many sounds so nicely like Firefox. I hope Chrome fixes the performance problems.

Regards, Alex

**Comment by charlieroberts** [comment]
Ok, the initSound bug is fixed; changes are pushed and online at gibber.cc. Thanks!

**Comment by Leetcore** [comment]
Thank you too! :+1:
