### ISSUE TITLE
'initSound already declared' still an error for gibber.lib.js

### ISSUE THREAD

**Issue by pippinbarr** [charlieroberts/Gibber#34]
A see from the tracking that this was fixed on gibber.cc, but this issue still exists in the version of gibber.lib.js available from github. I'm yet to understand how to download the library from gibber.cc - would it be possible to push the fix to the github as well?

**Comment by charlieroberts** [comment]
OK I believe this should be fixed. Let me know if you still have problems with it! - Charlie
